services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${SURVEY_DB_HOST}:${SURVEY_DB_PORT}/${SURVEY_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SURVEY_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SURVEY_DB_PASSWORD}
    depends_on:
      - db

  db:
    restart: always
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SURVEY_DB_USERNAME}
      - POSTGRES_PASSWORD=${SURVEY_DB_PASSWORD}
      - POSTGRES_DB=${SURVEY_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  gateway:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
