spring.application.name=review-service
server.port=8088

spring.threads.virtual.enabled=true

# Actuator
management.server.port=9090
management.server.address=127.0.0.1
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized
