apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: webstaurator
data:
  POSTGRES_HOST: postgres.webstaurator-infra.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: webstaurator_db
  REDIS_HOST: redis.webstaurator-infra.svc.cluster.local
  REDIS_PORT: "6379"
  JAEGER_HOST: jaeger.webstaurator-monitoring.svc.cluster.local
